zotero:
  user_id: "20414519"
  api_key: "wnjZprYbRQwAJBUkCFhNuXYc"
  include_path: null

email:
  sender: "18661622276@163.com"
  receiver: "18661622276@163.com"
  smtp_server: "smtp.163.com"
  smtp_port: 465
  sender_password: "QUUj5mWmwVmbg7TT"

llm:
  api:
    key: "sk-nrqiqfccplmjgrihlzafcehupqopelxbkabuvzdcnbtxnxny"
    base_url: "https://api.siliconflow.cn/v1"
  generation_kwargs:
    model: "gpt-4o-mini"

source:
  arxiv:
    category: ["cs.AI","cs.CV","cs.LG","cs.CL"]
    include_cross_list: false

executor:
  debug: false
  source: ["arxiv"]
