name: Test
on:
  workflow_dispatch:

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      #  with:
      #    repository: ${{ vars.REPOSITORY }}
      #    ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7.1.4


      - name: Run script
        env:
          CUSTOM_CONFIG: ${{ secrets.CUSTOM_CONFIG }}
        run: |
          export DEBUG=true
          # Write provided YAML to Hydra's config/custom.yaml.
          # IMPORTANT: do not echo the file contents (it contains secrets).
          printf "%s" "$CUSTOM_CONFIG" > config/custom.yaml
          uv run src/zotero_arxiv_daily/main.py
